### ISSUE TITLE
Host record for router's FQDN obscures interface address in PTR record

### ISSUE THREAD

**Issue by toreanderson** [sbyx/hnetd#54]
hnetd writes stuff like this to `/tmp/dnsmasq.d/hnet.conf`:

    host-record=rtr1.home.,10.0.123.32
    host-record=rtr1.home.,2001:db8:1234:d87::60
    host-record=rtr2.home.,10.0.79.14
    host-record=rtr2.home.,2001:db8:1234:d88::4e

The addresses used belong to a (randomly selected?) local interface on each router. This ensures that the routers can be accessed through their primary FQDNs. All well and good.

Unfortunately however, this also overrides the full PTR record (normally provided by ohybridproxy). For example, *32.123.0.10.in-addr.arpa.* will resolve to *rtr1.home.* instead of to *rtr1.interface1.rtr1.home.*. That in turn makes traceroutes through the Homenet look weird and lose information, because random hops will lack interface information.

This can possibly be avoided by using `cname` instead of `host-record`, or certainly by assigning "primary" addresses to a loopback/dummy interface of each router and use those when constructing the `host-record` lines in the dnsmasq config.

**Comment by fingon** [comment]
This is a good suggestion, however, the information is not really available. The data for <routername>.<ifname>.<routername>.<domain> is generated via hybrid proxy lookups, and is not published. 

The distributed database that is used to generate the dnsmasq conf in HNCP (soon-to-be-RFC7788) supports only A/AAAA records and not CNAMEs. Given a draft on the topic, I could change this, but not really otherwise (we assumed originally traceroute to be nice to have and opted for simplicity instead of 'everything').
